Update lattice plots
MastodonC/witan.send.adroddiad pull request #36
Opened 2022-11-30 16:36 UTC by seb231

2022-12-01 23:48 UTC, seb231 commented on src/witan/send/adroddiad/need_analysis.clj
>          (plotr/render-lattice size)
Breaks here, error report:
`                  RT.java: 1561  clojure.lang.RT/uncheckedDoubleCast
                  core.clj:   -1  fastmath.core/valid-double?
                  core.clj: 2586  clojure.core/comp/fn
                  core.clj: 2923  clojure.core/take-while/fn
              LazySeq.java:   42  clojure.lang.LazySeq/sval
              LazySeq.java:   51  clojure.lang.LazySeq/seq
                   RT.java:  535  clojure.lang.RT/seq
                  core.clj:  139  clojure.core/seq
                  core.clj:  139  clojure.core/seq
                  line.clj:   35  cljplot.impl.line/split-at-invalid-double
                  line.clj:   27  cljplot.impl.line/split-at-invalid-double
                  line.clj:   41  cljplot.impl.line/eval44664/fn
              MultiFn.java:  244  clojure.lang.MultiFn/invoke
                  AFn.java:  165  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  Var.java:  705  clojure.lang.Var/applyTo
                  core.clj:  667  clojure.core/apply
                  core.clj:  662  clojure.core/apply
                 debug.clj:  525  cider.nrepl.middleware.debug/apply-instrumented-maybe
                 debug.clj:  521  cider.nrepl.middleware.debug/apply-instrumented-maybe
                      REPL:   86  cljplot.render/eval69305/render-lattice-inner/fn/fn
                      REPL:   86  cljplot.render/eval69305/render-lattice-inner/fn
                      REPL:   77  cljplot.render/eval69305/render-lattice-inner
                  AFn.java:  160  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  Var.java:  705  clojure.lang.Var/applyTo
                  core.clj:  667  clojure.core/apply
                  core.clj:  662  clojure.core/apply
                 debug.clj:  525  cider.nrepl.middleware.debug/apply-instrumented-maybe
                 debug.clj:  521  cider.nrepl.middleware.debug/apply-instrumented-maybe
                      REPL:  150  cljplot.render/eval69338/render-lattice
         need_analysis.clj:  150  witan.send.adroddiad.need-analysis/need-analysis-chart`

2022-12-05 17:21 UTC, seb231 commented on src/witan/send/adroddiad/need_analysis.clj
>          (plotr/render-lattice size)
resolved

2022-12-07 14:00 UTC, eraderna requested changes
I think issues with stats for ncy/needs with 0 < :row-count < #simulations being over-estimated due to not accounting for the sims with no records as having a count of `0`.

2022-12-07 14:52 UTC, seb231 commented on src/witan/send/adroddiad/ncy_analysis.clj
> +                                          (-> (reduce #(tc/concat-copying %1 (tc/dataset {:low-95 0 :min 0 :q1 0 :q3 0 :median 0 :max 0 :row-count 1 :high-95 0 :calendar-year %2}))
good catch, missed in two places

2022-12-07 15:14 UTC, eraderna requested changes
Since the issue with stats with 0 < :row-count < #simulations being over-estimated was ~~not~~ prior and not introduced in this PR, agree can leave as is and address in a separate branch.

However, pending addressing this incomplete `:simulation :calendar-year` issue, suggest set `:row-count` to `0` (rather than `1`) in `fill-in-years`, so consistent.

2022-12-07 15:14 UTC, eraderna commented on src/witan/send/adroddiad/ncy_analysis.clj
> +                                              :max 0 :row-count 1 :high-95 0 :calendar-year %2}))
Pending addressing the incomplete `:simulation :calendar-year` issue, suggest set `:row-count` to `0` (rather than `1`), so consistent.

2022-12-07 15:14 UTC, eraderna commented on src/witan/send/adroddiad/need_analysis.clj
> +                                              :max 0 :row-count 1 :high-95 0 :calendar-year %2}))
Pending addressing the incomplete `:simulation :calendar-year` issue, suggest set `:row-count` to `0` (rather than `1`), so consistent.

2022-12-07 15:56 UTC, merged